inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'infrastructure/**/*'
    - 'vendor/**/*'

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'features/step_definitions/*.rb'

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - 'features/step_definitions/*.rb'

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
