language: ruby
bundler_args: --without=development --jobs=4
rvm:
  - 2.1.1
services:
  - couchdb
addons:
  firefox: "17.0"
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
env:
  global:
    - DISPLAY=":99.0"
    - RUBY_GC_HEAP_INIT_SLOTS="1000000"
    - RUBY_GC_HEAP_FREE_SLOTS="500000"
    - RUBY_GC_HEAP_GROWTH_FACTOR="1.1"
    - RUBY_GC_HEAP_GROWTH_MAX_SLOTS="10000000"
    - RUBY_GC_MALLOC_LIMIT_MAX="1000000000"
    - RUBY_GC_MALLOC_LIMIT_GROWTH_FACTOR="1.1"
before_script:
  - "bundle exec rake db:create_couch_sysadmin[rapidftr,rapidftr]"
  - "bundle exec rake sunspot:start"
  - "RAILS_ENV=cucumber bundle exec rake assets:precompile"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "RAILS_ENV=test bundle exec rake spec"
  - "RAILS_ENV=cucumber bundle exec rake cucumber:headless"
  - "RAILS_ENV=cucumber bundle exec rake cucumber:browser"
notifications:
  - email: false
