language: ruby
bundler_args: --without=development --jobs=4
rvm:
  - 2.1.1
services:
  - couchdb
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
env:
  global:
    - DISPLAY=":99.0"
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake db:create_couch_sysadmin[rapidftr,rapidftr]"
  - "bundle exec rake sunspot:start"
  - "RAILS_ENV=cucumber bundle exec rake assets:precompile"
script:
  - "RAILS_ENV=test bundle exec rake spec"
  - "RAILS_ENV=cucumber bundle exec rake cucumber:headless"
  - "RAILS_ENV=cucumber bundle exec rake cucumber:browser"
notifications:
  - email: false
