language: ruby
bundler_args: --without=development --jobs=4
rvm:
  - 1.9.3
services:
  - couchdb
addons:
  firefox: "17.0"
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
env:
  global:
    - "DISPLAY=:99.0"
    - "RUBY_HEAP_MIN_SLOTS=2000000"
    - "RUBY_HEAP_FREE_MIN=20000"
    - "RUBY_GC_MALLOC_LIMIT=100000000"
before_script:
  - "bundle exec rake db:create_couch_sysadmin[rapidftr,rapidftr]"
  - "bundle exec rake sunspot:start"
  - "RAILS_ENV=cucumber bundle exec rake assets:precompile"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "RAILS_ENV=test bundle exec rake spec"
  - "RAILS_ENV=test bundle exec rake cane:quality"
  - "RAILS_ENV=cucumber bundle exec rake cucumber:headless"
  - "RAILS_ENV=cucumber bundle exec rake cucumber:browser"
notifications:
  - email: false
