---
<% default_opts = "--format pretty --require capybara_features --strict --backtrace capybara_features" %>
<% std_opts = "--tags ~@wip #{default_opts}" %>
default: <%= std_opts %>
browser: --tags @javascript <%= std_opts %>
headless: --tags ~@javascript <%= std_opts %>
browser_wip: --tags @javascript --tags @wip:3 --wip <%= default_opts %>
headless_wip: --tags @headless --tags @wip:3 --wip <%= default_opts %>
